#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-ritis
Version  : 0.7.6
Release  : 12
URL      : https://cran.r-project.org/src/contrib/ritis_0.7.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ritis_0.7.6.tar.gz
Summary  : Integrated Taxonomic Information System Client
Group    : Development/Tools
License  : MIT
BuildRequires : R-data.table
BuildRequires : R-jsonlite
BuildRequires : R-plyr
BuildRequires : R-purrr
BuildRequires : R-solrium
BuildRequires : R-tibble
BuildRequires : R-triebeard
BuildRequires : R-urltools
BuildRequires : R-vcr
BuildRequires : R-yaml
BuildRequires : buildreq-R

%description
ritis
=====
[![Project Status: Active â The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/latest/active.svg)](http://www.repostatus.org/#active)
[![cran checks](https://cranchecks.info/badges/worst/ritis)](https://cranchecks.info/pkgs/ritis)
[![Build Status](https://travis-ci.org/ropensci/ritis.svg?branch=master)](https://travis-ci.org/ropensci/ritis)
[![Build status](https://ci.appveyor.com/api/projects/status/pvrc9muevha00fie/branch/master?svg=true)](https://ci.appveyor.com/project/sckott/ritis/branch/master)
[![codecov](https://codecov.io/gh/ropensci/ritis/branch/master/graph/badge.svg)](https://codecov.io/gh/ropensci/ritis)
[![rstudio mirror downloads](http://cranlogs.r-pkg.org/badges/ritis)](https://github.com/metacran/cranlogs.app)
[![cran version](http://www.r-pkg.org/badges/version/ritis)](https://cran.r-project.org/package=ritis)

%prep
%setup -q -c -n ritis

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552866595

%install
export SOURCE_DATE_EPOCH=1552866595
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ritis
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ritis
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ritis
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  ritis || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ritis/DESCRIPTION
/usr/lib64/R/library/ritis/INDEX
/usr/lib64/R/library/ritis/LICENSE
/usr/lib64/R/library/ritis/Meta/Rd.rds
/usr/lib64/R/library/ritis/Meta/data.rds
/usr/lib64/R/library/ritis/Meta/features.rds
/usr/lib64/R/library/ritis/Meta/hsearch.rds
/usr/lib64/R/library/ritis/Meta/links.rds
/usr/lib64/R/library/ritis/Meta/nsInfo.rds
/usr/lib64/R/library/ritis/Meta/package.rds
/usr/lib64/R/library/ritis/Meta/vignette.rds
/usr/lib64/R/library/ritis/NAMESPACE
/usr/lib64/R/library/ritis/NEWS.md
/usr/lib64/R/library/ritis/R/ritis
/usr/lib64/R/library/ritis/R/ritis.rdb
/usr/lib64/R/library/ritis/R/ritis.rdx
/usr/lib64/R/library/ritis/data/Rdata.rdb
/usr/lib64/R/library/ritis/data/Rdata.rds
/usr/lib64/R/library/ritis/data/Rdata.rdx
/usr/lib64/R/library/ritis/doc/index.html
/usr/lib64/R/library/ritis/doc/ritis_vignette.Rmd
/usr/lib64/R/library/ritis/doc/ritis_vignette.html
/usr/lib64/R/library/ritis/help/AnIndex
/usr/lib64/R/library/ritis/help/aliases.rds
/usr/lib64/R/library/ritis/help/paths.rds
/usr/lib64/R/library/ritis/help/ritis.rdb
/usr/lib64/R/library/ritis/help/ritis.rdx
/usr/lib64/R/library/ritis/html/00Index.html
/usr/lib64/R/library/ritis/html/R.css
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/any_match_count-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/any_match_count-json.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/any_match_count-xml.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/any_match_count.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/hierarchy-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/hierarchy_down.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/hierarchy_full.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/hierarchy_up.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/itis_facet.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/itis_group-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/itis_group.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/itis_highlight.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/itis_search-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/itis_search.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/jurisdiction_values.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/jurisdictional_origin-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/jurisdictional_origin.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/jurisdictional_origin_values.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/kingdom_name-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/kingdom_name.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/kingdom_names.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/publications-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/publications-json.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/publications-xml.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/publications.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/record-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/record-json.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/record-xml.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/record.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_common-fails-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_common-json.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_common-xml.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_common.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_scientific-fail-well.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_scientific-json.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_scientific-xml.yml
/usr/lib64/R/library/ritis/tests/fixtures/vcr_cassettes/search_scientific.yml
/usr/lib64/R/library/ritis/tests/test-all.R
/usr/lib64/R/library/ritis/tests/testthat/helper-ritis.R
/usr/lib64/R/library/ritis/tests/testthat/test-any_match_count.R
/usr/lib64/R/library/ritis/tests/testthat/test-hierarchy.R
/usr/lib64/R/library/ritis/tests/testthat/test-itis_facet.R
/usr/lib64/R/library/ritis/tests/testthat/test-itis_group.R
/usr/lib64/R/library/ritis/tests/testthat/test-itis_highlight.R
/usr/lib64/R/library/ritis/tests/testthat/test-itis_search.R
/usr/lib64/R/library/ritis/tests/testthat/test-jurisdiction.R
/usr/lib64/R/library/ritis/tests/testthat/test-kingdoms.R
/usr/lib64/R/library/ritis/tests/testthat/test-publications.R
/usr/lib64/R/library/ritis/tests/testthat/test-record.R
/usr/lib64/R/library/ritis/tests/testthat/test-search_common.R
/usr/lib64/R/library/ritis/tests/testthat/test-search_scientific.R
/usr/lib64/R/library/ritis/vign/ritis_vignette.Rmd
/usr/lib64/R/library/ritis/vign/ritis_vignette.md
